cache:
  paths:
    - node_modules/

stages:
  - test

test:node5:
  image: quay.io/help/node:5
  stage: test
  script:
    - npm install
    - npm test -- --coverage-report=text-summary

test:node6:
  image: quay.io/help/node:6
  stage: test
  script:
    - npm install
    - npm test -- --coverage-report=text-summary
